### ISSUE TITLE
Rename .Rmd files

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/dm#349]
to short and crisp titles:

```yaml
  - text: Tutorials
    menu:
    - text: Connect to a database
      href: articles/dm-db.html
    - text: Create a dm object from data frames
      href: articles/dm-df.html
    - text: Introduction to relational data models
      href: articles/dm-theory.html
  - text: Technical articles
    menu:
    - text: Class 'dm' and basic operations
      href: articles/dm-class.html
    - text: Visualizing 'dm' objects
      href: articles/dm-draw.html
    - text: Joining in relational data models
      href: articles/dm-join.html
    - text: Zooming and manipulating tables
      href: articles/dm-zoom.html
    - text: Filtering in relational data models
      href: articles/dm-filter.html
    - text: Low level operations
      href: articles/dm-low-level.html
    - text: Function naming logic
      href: articles/dm-naming.html
    - text: 'Migration guide: ''cdm'' -> ''dm'''
      href: articles/dm-cdm.html
```

## Script

```bash
from=visualization; to=draw; sed -i 's/dm-'$from'/dm-'$to'/g' *.Rmd ../pkgdown/_pkgdown.yml; mv dm-${from}.Rmd dm-${to}.Rmd
```
